import colors from '../../colors'

export default {
    background: colors.navy,
    backgroundAlt: colors.navyDark,
    backgroundInverted: '#aac6c9',
    text: '#9ac6c9',
    textInverted: colors.navyDark,
    textHighlight: colors.greenDark,
    link: colors.pink,
    linkActive: colors.greenDark,
    contrast: '#0bdf67',
    border: '#9ac6c9',
    heatmap: colors.pinkLight,
    lineChartDefaultColor: '#59DF7F',
    barChartDefaultColor: colors.blue,
    ranges: {
        tools: {
            would_use: colors.pink,
            would_not_use: colors.pinkLight,
            interested: '#59DF7F',
            not_interested: '#ACFFC3',
            never_heard: '#59608a',
        },
        features: {
            used: colors.blue,
            heard: '#9AC6C9',
            never_heard: colors.navyLighter,
        },
        features_simplified: {
            know_it: '#ACFFC3',
            used_it: '#59DF7F',
        },
        gender: {
            male: colors.blue,
            female: colors.teal,
            non_binary: colors.red,
            prefer_not_to_say: colors.greyMediumer,
        },
        opinions: {
            4: colors.pink,
            3: colors.pinkLight,
            2: '#59608a',
            1: colors.blueLight,
            0: colors.blue,
        },
    },
    distinct: [
        colors.indigo,
        colors.teal,
        colors.pink,
        colors.red,
        colors.green,
        colors.yellow,
        colors.aqua,
        colors.orange,
        colors.olive,
        colors.skyblue,
        colors.purple,
    ],
    countries: [
        colors.blue,
        colors.blueLight,
        colors.blueLighter,
        colors.pinkLightest,
        colors.pinkLighter,
        colors.pinkLight,
        colors.pink,
    ],
}
